# Generated by Django 5.1.5 on 2025-02-09 07:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latest_update', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('serial_number', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temparature', models.IntegerField()),
            ],
            options={
                'ordering': ['temparature'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wire1_id', models.CharField(max_length=100, unique=True)),
                ('depth', models.IntegerField()),
                ('alarm', models.IntegerField(default=25)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'ordering': ['chain'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField()),
                ('value', models.FloatField()),
                ('alarm_state', models.IntegerField(choices=[(2, 'Cleared'), (1, 'In alarm'), (0, 'No alarm')], default=0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'ordering': ['recorded'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('average', models.FloatField()),
                ('high', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField()),
                ('value', models.FloatField()),
                ('alarm_state', models.IntegerField(choices=[(2, 'Cleared'), (1, 'In alarm'), (0, 'No alarm')], default=0)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
            ],
            options={
                'ordering': ['recorded'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.FloatField()),
                ('recorded', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('internal_temp', models.FloatField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chain')),
            ],
            options={
                'ordering': ['chain'],
            },
        ),
    ]
